title:               Jacky Hoh
url:                 https://jackyhohs.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Jacky Hoh
  url:               jackyhohs.github.io
  email:             jacky.hoh2@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist